apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    k8s-app: frp
    qcloud-app: frp
  name: frp
  namespace: development
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: frp
      qcloud-app: frp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: frp
        qcloud-app: frp
    spec:
      containers:
      - image: cloverzrg/frps-docker:0.33.0
        imagePullPolicy: IfNotPresent
        name: frp
        resources:
          limits:
            cpu: 94m
            memory: 141Mi
          requests:
            cpu: 90m
            memory: 138Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /conf
          name: nfs
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nfs
        nfs:
          path: /volumes/frp
          server: 10.10.4.4