apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    k8s-app: gitea
    qcloud-app: gitea
  name: gitea
  namespace: development
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: gitea
      qcloud-app: gitea
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: gitea
        qcloud-app: gitea
    spec:
      containers:
      - env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: DB_HOST
              name: gitea
              optional: false
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              key: DB_NAME
              name: gitea
              optional: false
        - name: DB_PASSWD
          valueFrom:
            configMapKeyRef:
              key: DB_PASSWD
              name: gitea
              optional: false
        - name: DB_TYPE
          valueFrom:
            configMapKeyRef:
              key: DB_TYPE
              name: gitea
              optional: false
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              key: DB_USER
              name: gitea
              optional: false
        - name: USER_GID
          valueFrom:
            configMapKeyRef:
              key: USER_GID
              name: gitea
              optional: false
        - name: USER_UID
          valueFrom:
            configMapKeyRef:
              key: USER_UID
              name: gitea
              optional: false
        image: gitea/gitea:1.11.1-linux-amd64
        imagePullPolicy: IfNotPresent
        name: gitea
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: nfs
          subPath: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nfs
        nfs:
          path: /volumes/gitea
          server: 10.10.4.4
