apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    k8s-app: ldap-self-service-password
    qcloud-app: ldap-self-service-password
  name: ldap-self-service-password
  namespace: development
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: ldap-self-service-password
      qcloud-app: ldap-self-service-password
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: ldap-self-service-password
        qcloud-app: ldap-self-service-password
    spec:
      containers:
      - image: surenkid/docker-ldap-self-service-password:latest
        imagePullPolicy: Always
        name: ldap-self-service-password
        resources:
          limits:
            cpu: 94m
            memory: 141Mi
          requests:
            cpu: 90m
            memory: 138Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/html/conf
          name: nfs
          readOnly: true
          subPath: self-service-password-conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nfs
        nfs:
          path: /volumes/openldap
          server: 10.10.4.4
