apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    k8s-app: mindoc
    qcloud-app: mindoc
  name: mindoc
  namespace: development
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: mindoc
      qcloud-app: mindoc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: mindoc
        qcloud-app: mindoc
    spec:
      containers:
      - env:
        - name: MINDOC_RUN_MODE
          value: prod
        - name: MINDOC_DB_ADAPTER
          value: mysql
        - name: MINDOC_DB_HOST
          value: 10.10.4.5
        - name: MINDOC_DB_DATABASE
          value: "mindoc"
        - name: MINDOC_DB_USERNAME
          value: mindoc
        - name: MINDOC_DB_PASSWORD
          value: password
        - name: MINDOC_CACHE
          value: "true"
        - name: MINDOC_LDAP_ENABLE
          value: "true"
        - name: MINDOC_LDAP_HOST
          value: openldap
        - name: MINDOC_LDAP_PORT
          value: "389"
        - name: MINDOC_LDAP_ATTRIBUTE
          value: uid
        - name: MINDOC_LDAP_BASE
          value: dc=ktsee,dc=com
        - name: MINDOC_LDAP_USER
          value: cn=admin,dc=ktsee,dc=com
        - name: MINDOC_LDAP_PASSWORD
          value: password
        image: surenkid/mindoc:2.0
        imagePullPolicy: IfNotPresent
        name: mindoc
        resources:
          limits:
            cpu: 235m
            memory: 352Mi
          requests:
            cpu: 225m
            memory: 345Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mindoc/conf
          name: nfs
          subPath: conf
        - mountPath: /mindoc/uploads
          name: nfs
          subPath: uploads
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nfs
        nfs:
          path: /volumes/mindoc
          server: 10.10.4.4
