apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    description: openldap
  generation: 1
  labels:
    k8s-app: openldap
    qcloud-app: openldap
  name: openldap
  namespace: development
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: openldap
      qcloud-app: openldap
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: openldap
        qcloud-app: openldap
    spec:
      containers:
      - env:
        - name: LDAP_LOG_LEVEL
          value: "256"
        - name: LDAP_ORGANISATION
          value: ktsee.com
        - name: LDAP_DOMAIN
          value: ktsee.com
        - name: LDAP_ADMIN_PASSWORD
          value: password
        - name: LDAP_CONFIG_PASSWORD
          value: config
        - name: LDAP_READONLY_USER
          value: "false"
        - name: LDAP_READONLY_USER_USERNAME
          value: readonly
        - name: LDAP_READONLY_USER_PASSWORD
          value: readonly
        - name: LDAP_RFC2307BIS_SCHEMA
          value: "false"
        - name: LDAP_BACKEND
          value: mdb
        - name: LDAP_TLS
          value: "true"
        - name: LDAP_TLS_CRT_FILENAME
          value: ldap.crt
        - name: LDAP_TLS_KEY_FILENAME
          value: ldap.key
        - name: LDAP_TLS_DH_PARAM_FILENAME
          value: dhparam.pem
        - name: LDAP_TLS_CA_CRT_FILENAME
          value: ca.crt
        - name: LDAP_TLS_ENFORCE
          value: "false"
        - name: LDAP_TLS_CIPHER_SUITE
          value: "SECURE256:+SECURE128:-VERS-TLS-ALL:+VERS-TLS1.2:-RSA:-DHE-DSS:-CAMELLIA-128-CBC:-CAMELLIA-256-CBC"
        - name: LDAP_TLS_VERIFY_CLIENT
          value: demand
        - name: LDAP_REPLICATION
          value: "false"
        - name: LDAP_REPLICATION_CONFIG_SYNCPROV
          value: binddn="cn=admin,cn=config" bindmethod=simple credentials=$LDAP_CONFIG_PASSWORD searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 starttls=critical
        - name: LDAP_REPLICATION_DB_SYNCPROV
          value: binddn="cn=admin,$LDAP_BASE_DN" bindmethod=simple credentials=$LDAP_ADMIN_PASSWORD searchbase="$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical
        - name: LDAP_REPLICATION_HOSTS
          value: "#PYTHON2BASH:['ldap://ldap-one-service', 'ldap://ldap-two-service']"
        - name: KEEP_EXISTING_CONFIG
          value: "false"
        - name: LDAP_REMOVE_CONFIG_AFTER_SETUP
          value: "true"
        - name: LDAP_SSL_HELPER_PREFIX
          value: ldap
        image: osixia/openldap:1.3.0
        imagePullPolicy: IfNotPresent
        name: openldap
        resources:
          limits:
            cpu: 94m
            memory: 141Mi
          requests:
            cpu: 90m
            memory: 138Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/ldap
          name: nfs
          subPath: data
        - mountPath: /etc/ldap/slapd.d
          name: nfs
          subPath: config
        - mountPath: /container/service/slapd/assets/certs
          name: nfs
          subPath: certs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nfs
        nfs:
          path: /volumes/openldap
          server: 10.10.4.4
