apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    description: openldap
  generation: 1
  labels:
    k8s-app: openldap
    qcloud-app: openldap
  name: openldap
  namespace: development
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: openldap
      qcloud-app: openldap
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: openldap
        qcloud-app: openldap
    spec:
      containers:
      - env:
        - name: LDAP_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              key: LDAP_LOG_LEVEL
              name: openldap
              optional: false
        - name: LDAP_ORGANISATION
          valueFrom:
            configMapKeyRef:
              key: LDAP_ORGANISATION
              name: openldap
              optional: false
        - name: LDAP_DOMAIN
          valueFrom:
            configMapKeyRef:
              key: LDAP_DOMAIN
              name: openldap
              optional: false
        - name: LDAP_ADMIN_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: LDAP_ADMIN_PASSWORD
              name: openldap
              optional: false
        - name: LDAP_CONFIG_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: LDAP_CONFIG_PASSWORD
              name: openldap
              optional: false
        - name: LDAP_READONLY_USER
          valueFrom:
            configMapKeyRef:
              key: LDAP_READONLY_USER
              name: openldap
              optional: false
        - name: LDAP_READONLY_USER_USERNAME
          valueFrom:
            configMapKeyRef:
              key: LDAP_READONLY_USER_USERNAME
              name: openldap
              optional: false
        - name: LDAP_READONLY_USER_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: LDAP_READONLY_USER_PASSWORD
              name: openldap
              optional: false
        - name: LDAP_RFC2307BIS_SCHEMA
          valueFrom:
            configMapKeyRef:
              key: LDAP_RFC2307BIS_SCHEMA
              name: openldap
              optional: false
        - name: LDAP_BACKEND
          valueFrom:
            configMapKeyRef:
              key: LDAP_BACKEND
              name: openldap
              optional: false
        - name: LDAP_TLS
          valueFrom:
            configMapKeyRef:
              key: LDAP_TLS
              name: openldap
              optional: false
        - name: LDAP_TLS_CRT_FILENAME
          valueFrom:
            configMapKeyRef:
              key: LDAP_TLS_CRT_FILENAME
              name: openldap
              optional: false
        - name: LDAP_TLS_KEY_FILENAME
          valueFrom:
            configMapKeyRef:
              key: LDAP_TLS_KEY_FILENAME
              name: openldap
              optional: false
        - name: LDAP_TLS_DH_PARAM_FILENAME
          valueFrom:
            configMapKeyRef:
              key: LDAP_TLS_DH_PARAM_FILENAME
              name: openldap
              optional: false
        - name: LDAP_TLS_CA_CRT_FILENAME
          valueFrom:
            configMapKeyRef:
              key: LDAP_TLS_CA_CRT_FILENAME
              name: openldap
              optional: false
        - name: LDAP_TLS_ENFORCE
          valueFrom:
            configMapKeyRef:
              key: LDAP_TLS_ENFORCE
              name: openldap
              optional: false
        - name: LDAP_TLS_CIPHER_SUITE
          valueFrom:
            configMapKeyRef:
              key: LDAP_TLS_CIPHER_SUITE
              name: openldap
              optional: false
        - name: LDAP_TLS_VERIFY_CLIENT
          valueFrom:
            configMapKeyRef:
              key: LDAP_TLS_VERIFY_CLIENT
              name: openldap
              optional: false
        - name: LDAP_REPLICATION
          valueFrom:
            configMapKeyRef:
              key: LDAP_REPLICATION
              name: openldap
              optional: false
        - name: LDAP_REPLICATION_CONFIG_SYNCPROV
          valueFrom:
            configMapKeyRef:
              key: LDAP_REPLICATION_CONFIG_SYNCPROV
              name: openldap
              optional: false
        - name: LDAP_REPLICATION_DB_SYNCPROV
          valueFrom:
            configMapKeyRef:
              key: LDAP_REPLICATION_DB_SYNCPROV
              name: openldap
              optional: false
        - name: LDAP_REPLICATION_HOSTS
          valueFrom:
            configMapKeyRef:
              key: LDAP_REPLICATION_HOSTS
              name: openldap
              optional: false
        - name: KEEP_EXISTING_CONFIG
          valueFrom:
            configMapKeyRef:
              key: KEEP_EXISTING_CONFIG
              name: openldap
              optional: false
        - name: LDAP_REMOVE_CONFIG_AFTER_SETUP
          valueFrom:
            configMapKeyRef:
              key: LDAP_REMOVE_CONFIG_AFTER_SETUP
              name: openldap
              optional: false
        - name: LDAP_SSL_HELPER_PREFIX
          valueFrom:
            configMapKeyRef:
              key: LDAP_SSL_HELPER_PREFIX
              name: openldap
              optional: false

        image: osixia/openldap:1.3.0
        imagePullPolicy: IfNotPresent
        name: openldap
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/ldap
          name: nfs
          subPath: data
        - mountPath: /etc/ldap/slapd.d
          name: nfs
          subPath: config
        - mountPath: /container/service/slapd/assets/certs
          name: nfs
          subPath: certs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nfs
        nfs:
          path: /volumes/openldap
          server: 10.10.4.4
