apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    k8s-app: redisinsight
    qcloud-app: redisinsight
  name: redisinsight
  namespace: development
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: redisinsight
      qcloud-app: redisinsight
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: redisinsight
        qcloud-app: redisinsight
    spec:
      containers:
      - env:
        - name: REDISINSIGHT_HOST
          value: 0.0.0.0
        - name: REDISINSIGHT_PORT
          value: "8001"
        - name: REDISINSIGHT_HOME_DIR
          value: /db
        - name: LOG_DIR
          value: /tmp
        image: redislabs/redisinsight:1.6.2
        imagePullPolicy: IfNotPresent
        name: redisinsight
        resources:
          limits:
            cpu: 94m
            memory: 141Mi
          requests:
            cpu: 90m
            memory: 138Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /db
          name: nfs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nfs
        nfs:
          path: /volumes/redisinsight
          server: 10.10.4.4