apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    k8s-app: rsshub
    qcloud-app: rsshub
  name: rsshub
  namespace: development
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: rsshub
      qcloud-app: rsshub
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: rsshub
        qcloud-app: rsshub
    spec:
      containers:
      - image: diygod/rsshub:latest
        imagePullPolicy: Always
        name: rsshub
        resources:
          limits:
            cpu: 470m
            memory: 705Mi
          requests:
            cpu: 450m
            memory: 690Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30