apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    k8s-app: redmine
    qcloud-app: redmine
  name: redmine
  namespace: development
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: redmine
      qcloud-app: redmine
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: redmine
        qcloud-app: redmine
    spec:
      containers:
      - env:
        - name: REDMINE_DB_MYSQL
          value: 10.10.4.5
        - name: REDMINE_DB_PORT
          value: "3306"
        - name: REDMINE_DB_USERNAME
          value: redmine
        - name: REDMINE_DB_DATABASE
          value: redmine
        - name: REDMINE_DB_ENCODING
          value: utf8
        - name: REDMINE_NO_DB_MIGRATE
          value: "true"
        - name: REDMINE_PLUGINS_MIGRATE
          value: "true"
        - name: REDMINE_SECRET_KEY_BASE
          value: surenkids@gmail.com
        - name: REDMINE_DB_PASSWORD
          value: password
        image: redmine:4.0.7-alpine
        imagePullPolicy: IfNotPresent
        name: redmine
        resources:
          limits:
            cpu: 235m
            memory: 352Mi
          requests:
            cpu: 225m
            memory: 345Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/src/redmine/config
          name: nfs
          subPath: config
        - mountPath: /usr/src/redmine/files
          name: nfs
          subPath: files
        - mountPath: /usr/src/redmine/public/themes
          name: nfs
          subPath: themes
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nfs
        nfs:
          path: /volumes/redmine
          server: 10.10.4.4