version: '3'
services:
  openldap:
    image: osixia/openldap:1.1.7
    restart: always
    container_name: openldap-main
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "sumeils.com"
      LDAP_DOMAIN: "sumeils.com"
      LDAP_BASE_DN: "dc=sumeils,dc=com"
      LDAP_ADMIN_PASSWORD: "password"
      #LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: "readonly"
      LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_BACKEND: "hdb"
      #LDAP_TLS: "true"
      #LDAP_TLS_CRT_FILENAME: "cert.pem"
      #LDAP_TLS_KEY_FILENAME: "privkey.pem"
      #LDAP_TLS_CA_CRT_FILENAME: "ca.pem"
      #LDAP_TLS_ENFORCE: "false"
      #LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      #LDAP_TLS_PROTOCOL_MIN: "3.1"
      #LDAP_TLS_VERIFY_CLIENT: "demand"
      #LDAP_SSL_HELPER_PREFIX: "ldap"
      LDAP_REPLICATION: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
    tty: true
    stdin_open: true
    volumes:
      - "./openldap/ldap:/var/lib/ldap"
      - "./openldap/slapd.d:/etc/ldap/slapd.d"
      #- "./openldap/certs:/container/service/slapd/assets/certs"
    ports:
      - "389:389"
      - "639:639"
    hostname: "ldap"

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: openldap-phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8082:80"
    depends_on:
      - openldap
