version: "3"
services:
  php:
    image: surenkid/docker-zf2:latest
    container_name: zf2-webserver
    ports:
      - "80:80"
    depends_on:
      - "mysql"
      - "postgres"
      - "solr"
      - "elasticsearch"
    volumes:
      - "./wwwroot:/zf2-app"

  mysql:
    image: mysql:5.7.16
    container_name: zf2-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
      #- "./dbdump:/root"
    environment:
      MYSQL_ROOT_PASSWORD: "surenkid"

  postgres:
    image: postgres:9.0.22
    container_name: zf2-postgres
    ports:
      - "5432:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
      #- "./dbdump:/root"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"

  solr:
    image: solr:5.5.4
    container_name: zf2-solr
    ports:
      - "8983:8983"
    volumes:
      - "./solr:/opt/solr/server/solr/mycores"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
      
  elasticsearch:
    image: elasticsearch:5.6.9
    container_name: zf2-elasticsearch
    ports:
      - "9200:9200"
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "./elasticsearch:/usr/share/elasticsearch/data"
      
  logstash:
    build: ./logstash
    container_name: zf2-logstash
    volumes:
      - "./logstash:/config-dir"
    command: logstash -f /config-dir/logstash.conf
    depends_on:
      - elasticsearch
      - mysql