apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: development
spec:
  clusterIP: None
  ports:
  - name: 3306-3306-tcp
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    k8s-app: mysql
    qcloud-app: mysql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}