apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  namespace: development
spec:
  ports:
  - name: 3306-3306-tcp
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    k8s-app: mysql-master
    qcloud-app: mysql-master
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}