version: "3"

services:
  ftp:
    image: surenkid/ktsee-ftp:latest
    volumes:
      - "ftp_www:/home"
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    environment:
      PASSWORD: ${pass}
      PASV_ENABLE: "YES"
      PASV_ADDRESS: ${ip}
      PASV_ADDR_RESOLVE: "NO"
      PASV_MIN_PORT: 21100
      PASV_MAX_PORT: 21110
      IGNORE_PERMISSION: "YES"
    deploy: 
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

volumes:
  ftp_www:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${nfs},vers=4,soft,rw
      device: ":/volumes/web"