version: "3"

services:
  mongodb:
    image: mongo:4.0.18
    ports:
      - "27017:27017"
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: ${pass}
    volumes:
      - "mongo_db:/data/db"
      - "mongo_config:/data/configdb"
    deploy: 
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.hostname == VM_3_22_coreos]

volumes:
  mongo_db:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${nfs2},vers=4,soft,rw
      device: ":/volumes/mongo/db"
  mongo_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${nfs},vers=4,soft,rw
      device: ":/volumes/mongo/config"