version: "3"

services:
  mysql:
    image: mysql:5.7.30
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${pass}
    volumes:
      - "mysql_db:/var/lib/mysql"
      - "mysql_config:/etc/mysql"
    deploy: 
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.hostname == VM_3_22_coreos]

volumes:
  mysql_db:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${nfs2},vers=4,soft,rw
      device: ":/volumes/mysql/db"
  mysql_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${nfs},vers=4,soft,rw
      device: ":/volumes/mysql/config"