apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    description: gapi.sumeils.com
  labels:
    k8s-app: global-api
    qcloud-app: global-api
  name: global-api
  namespace: production
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: global-api
      qcloud-app: global-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: global-api
        qcloud-app: global-api
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: qcloud-app
                operator: In
                values:
                - global-api
            topologyKey: "kubernetes.io/hostname"
      containers:
      - image: nginx:1.17.10-alpine
        imagePullPolicy: IfNotPresent
        name: nginx
        resources:
          limits:
            cpu: 320m
            memory: 470Mi
          requests:
            cpu: 300m
            memory: 460Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx
          name: nfs
          readOnly: true
          subPath: nginx
        - mountPath: /var/www/html
          name: local-www
      - image: surenkid/ktsee-cron-rsync:latest
        imagePullPolicy: Always
        name: cron-sync
        readinessProbe:
          exec:
            command:
            - sh
            - /root/readiness-probe.sh
          failureThreshold: 1
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          limits:
            cpu: 150m
            memory: 235Mi
          requests:
            cpu: 150m
            memory: 230Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/remote
          name: nfs
          subPath: web
        - mountPath: /var/www/html
          name: local-www
      - image: surenkid/ktsee-php:5.3-fpm
        imagePullPolicy: IfNotPresent
        name: php53
        resources:
          limits:
            cpu: 470m
            memory: 705Mi
          requests:
            cpu: 450m
            memory: 690Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/local/etc/php
          name: nfs
          readOnly: true
          subPath: php
        - mountPath: /usr/local/etc/php-fpm.d
          name: nfs
          readOnly: true
          subPath: php-fpm.d
        - mountPath: /var/www/html
          name: local-www
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: qcloudregistrykey
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nfs
        nfs:
          path: /volumes/app/gapi.sumeils.com
          server: 10.10.3.4
      - emptyDir: {}
        name: local-www
