apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    k8s-app: php72-supervisor
    qcloud-app: php72-supervisor
  name: php72-supervisor
  namespace: production
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: php72-supervisor
      qcloud-app: php72-supervisor
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: php72-supervisor
        qcloud-app: php72-supervisor
    spec:
      containers:
      - image: surenkid/ktsee-php:7.2-fpm-supervisor
        imagePullPolicy: Always
        name: php72-supervisor
        readinessProbe:
          exec:
            command:
            - sh
            - /root/readiness-probe.sh
          failureThreshold: 1
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          limits:
            cpu: 3720m
            memory: 6175Mi
          requests:
            cpu: 3610m
            memory: 6061Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/supervisor.d
          name: nfs
          readOnly: true
          subPath: app/php72-supervisord/supervisor.d
        - mountPath: /etc/crontabs
          name: nfs
          readOnly: true
          subPath: app/php72-supervisord/crontabs
        - mountPath: /usr/local/etc/php-fpm.d
          name: nfs
          readOnly: true
          subPath: app/php72-supervisord/php-fpm.d
        - mountPath: /root/remote
          name: nfs
          subPath: app
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: qcloudregistrykey
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nfs
        nfs:
          path: /volumes
          server: 10.10.3.4