apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    k8s-app: website-sumeils
    qcloud-app: website-sumeils
  name: website-sumeils
  namespace: production
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: website-sumeils
      qcloud-app: website-sumeils
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: website-sumeils
        qcloud-app: website-sumeils
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: qcloud-app
                operator: In
                values:
                - website-sumeils
            topologyKey: kubernetes.io/hostname
      containers:
      - image: nginx:1.17.10-alpine
        imagePullPolicy: IfNotPresent
        name: nginx
        resources:
          limits:
            cpu: 376m
            memory: 564Mi
          requests:
            cpu: 360m
            memory: 552Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx
          name: nfs
          readOnly: true
          subPath: nginx
        - mountPath: /var/www/html
          name: local-www
      - image: surenkid/ktsee-cron-rsync:latest
        imagePullPolicy: Always
        name: cron-sync
        readinessProbe:
          exec:
            command:
            - sh
            - /root/readiness-probe.sh
          failureThreshold: 1
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          limits:
            cpu: 94m
            memory: 141Mi
          requests:
            cpu: 90m
            memory: 138Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/remote
          name: nfs
          subPath: web
        - mountPath: /var/www/html
          name: local-www
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: qcloudregistrykey
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nfs
        nfs:
          path: /volumes/app/www.sumeils.com
          server: 10.10.3.4
      - emptyDir: {}
        name: local-www