version: "3"
services:
  nginx:
    image: nginx:1.15-alpine
    container_name: tp5-nginx
    ports:
      - "80:80"
    networks:
      - "php7net"
    depends_on:
      - "php"
    volumes:
      - "./nginx:/etc/nginx/conf.d"
      - "./wwwroot:/var/www/html:ro"

  php:
    image: surenkid/php7:latest
    container_name: tp5-php
    ports:
      - "9000:9000"
    networks:
      - "php7net"
    depends_on:
      - "mysql"
      - "redis"
    volumes:
      - "./php/php.ini:/usr/local/etc/php/php.ini"
      - "./wwwroot:/var/www/html"

  mysql:
    image: mysql:5.7
    container_name: tp5-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    networks:
      - "php7net"
    volumes:
      - "./mysql:/var/lib/mysql"
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: "surenkid"

  redis:
    image: redis:4-alpine
    container_name: tp5-redis
    ports:
      - "6379:6379"
    networks:
      - "php7net"
    volumes:
      - "./redis:/data"

networks:
  php7net:
