version: "3"
services:
  nginx:
    image: nginx:1.12-alpine
    container_name: tp3-nginx
    ports:
      - "80:80"
    networks:
      - "php53net"
    depends_on:
      - "php"
    volumes:
      - "./nginx:/etc/nginx/conf.d"
      - "./wwwroot:/var/www/html:ro"

  php:
    image: surenkid/php53:latest
    container_name: tp3-php
    ports:
      - "9000:9000"
    networks:
      - "php53net"
    depends_on:
      - "mysql"
      - "redis"
    volumes:
      - "./wwwroot:/var/www/html"

  mysql:
    image: mysql:5.6.36
    container_name: tp3-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    networks: 
      - "php53net"
    volumes:
      - "./mysql:/var/lib/mysql"
      # - "./dbdump:/root"
    environment:
      MYSQL_ROOT_PASSWORD: "surenkid"

  redis:
    image: redis:3.0-alpine
    container_name: tp3-redis
    ports:
      - "6379:6379"
    networks: 
      - "php53net"
    volumes:
      - "./redis:/data"

networks: 
  php53net: